export const cities = [
    { code: 'GVA', name: 'Geneve, Suisse' },
    { code: 'ZRH', name: 'Zurich, Suisse' },
    { code: 'LYS', name: 'Lyon, France' },
    { code: 'MRS', name: 'Marseille, France' },
    { code: 'PAR', name: 'Paris, France' },
    { code: 'MLH', name: 'Mulhouse, France' },
    { code: 'TLS', name: 'Toulouse, France' },
    { code: 'MPL', name: 'Montpellier, France' },
    { code: 'NCE', name: 'Nice, France' },
    { code: 'BOD', name: 'Bordeaux, France' },
    { code: 'ALG', name: 'Alger, Algerie' },
    { code: 'CZL', name: 'Constantine, Algerie' },
    { code: 'BJA', name: 'Bejaia, Algerie' },
    { code: 'QSF', name: 'Setif, Algerie' },
    { code: 'ORN', name: 'Oran, Algerie' },
    { code: 'BLJ', name: 'Batna, Algerie' },
    { code: 'BSK', name: 'Biskra, Algerie' },
    { code: 'TLM', name: 'Tlemcen, Algerie' },
    { code: 'TUN', name: 'Tunis, Tunisie' },
    { code: 'MIR', name: 'Monastir, Tunisie' },
    { code: 'DJE', name: 'Djerba, Tunisie' },
    { code: 'NBE', name: 'Enfidha, Tunisie' },
    { code: 'CMN', name: 'Casablanca, Maroc' },
    { code: 'TNG', name: 'Tanger, Maroc' },
    { code: 'RBA', name: 'Rabat, Maroc' },
    { code: 'RAK', name: 'Marrakech, Maroc' },
    { code: 'NDR', name: 'Nador, Maroc' },
    { code: 'FEZ', name: 'Fez, Maroc' },
    { code: 'DSS', name: 'Dakar, Senegal' },
    { code: 'LFW', name: 'Lome, Togo' },
    { code: 'CKY', name: 'Conakry, Guinée' },
    { code: 'OXB', name: 'Bissau, Guinée-Bissau' },
    { code: 'RAI', name: 'Praia, Cap-Vert' },
    { code: 'ABJ', name: 'Abidjan, Côte d\'Ivoire' },
    { code: 'YAO', name: 'Yaoundé, Cameroun' },
    { code: 'DLA', name: 'Douala, Cameroun' },
    { code: 'FIH', name: 'Kinshasa, République démocratique du Congo' },
    { code: 'ABV', name: 'Abuja, Nigeria' },
    { code: 'LOS', name: 'Lagos, Nigeria' },
    { code: 'KRT', name: 'Khartoum, Soudan' },
    { code: 'ADD', name: 'Addis-Abeba, Éthiopie' },
    { code: 'BKO', name: 'Bamako, Mali' },
    { code: 'NBO', name: 'Nairobi, Kenya' },
    { code: 'TNR', name: 'Antananarivo, Madagascar' },
    { code: 'YVA', name: 'Moroni, Comores' },
    { code: 'BJL', name: 'Banjul, Gambie' },
    { code: 'ACC', name: 'Accra, Ghana' },
    { code: 'NKC', name: 'Nouakchott, Mauritanie' },
    { code: 'TIP', name: 'Tripoli, Libye' },
    { code: 'CAI', name: 'Le Caire, Égypte' },
    { code: 'HRG', name: 'Hurghada, Égypte' },
    { code: 'OUA', name: 'Ouagadougou, Burkina Faso' },
    { code: 'LBV', name: 'Libreville, Gabon' },
    { code: 'LAD', name: 'Luanda, Angola' },
    { code: 'FNA', name: 'Freetown, Sierra Leone' },
    { code: 'ASM', name: 'Asmara, Érythrée' },
    { code: 'IST', name: 'Istanbul, Turquie' },
    { code: 'ANK', name: 'Ankara, Turquie' },
    { code: 'BJV', name: 'Bodrum-Milas, Turquie' },
    { code: 'AYT', name: 'Antalya, Turquie' },
    { code: 'GZT', name: 'Gaziantep, Turquie' },
    { code: 'RUH', name: 'Riyad, Arabie Saoudite' },
    { code: 'JED', name: 'Djeddah, Arabie Saoudite' },
    { code: 'MED', name: 'Médine, Arabie Saoudite' },
    { code: 'AUH', name: 'Abu Dhabi, Émirats Arabes Unis' },
    { code: 'DXB', name: 'Dubaï, Émirats Arabes Unis' },
    { code: 'KWI', name: 'Koweït, Koweït' },
    { code: 'DOH', name: 'Doha, Qatar' },
    { code: 'MCT', name: 'Mascate, Oman' },
    { code: 'BAH', name: 'Manama, Bahreïn' },
    { code: 'ISB', name: 'Islamabad, Pakistan' },
    { code: 'LHE', name: 'Lahore, Pakistan' },
    { code: 'KHI', name: 'Karachi, Pakistan' },
    { code: 'BKK', name: 'Bangkok, Thaïlande' },
    { code: 'HKT', name: 'Phuket, Thaïlande' },
    { code: 'KUL', name: 'Kuala Lumpur, Malaisie' },
    { code: 'CGK', name: 'Jakarta, Indonésie' },
    { code: 'ICN', name: 'Séoul, Corée du Sud' },
    { code: 'NRT', name: 'Tokyo, Japon' },
    { code: 'OSA', name: 'Osaka, Japon' },
    { code: 'PEK', name: 'Pékin, Chine' },
    { code: 'HAN', name: 'Hanoï, Vietnam' },
    { code: 'SGN', name: 'Hô Chi Minh-Ville, Vietnam' },
    { code: 'YOW', name: 'Ottawa, Canada' },
    { code: 'YYZ', name: 'Toronto, Canada' },
    { code: 'YQB', name: 'Québec, Canada' },
    { code: 'YUL', name: 'Montréal, Canada' },
    { code: 'IAD', name: 'Washington, USA' },
    { code: 'NYC', name: 'New York, USA' }
  ];
  